version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5439:5439

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080

#  fhirResourceManager:
#    build: .
#    ports:
#      - 8080:8080
#    environment:
#      SUBSYSTEMS_DB_HOST: db
#      SUBSYSTEMS_DB_PORT: 5432
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_USER: postgres