version: '3.1'

services:
  db:
    image: postgres:9.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  fhirResourceManager:
    image: fhir-resource-manager:1.0
    ports:
      - 8080:8080
